#!/usr/bin/env bash
set -e

PROJECT_DIR="/opt/shvirtd-example-python"
BACKUP_DIR="/opt/backup"
DATE=$(date +%Y%m%d_%H%M%S)

if [ -f "$PROJECT_DIR/.env" ]; then
  export $(grep -v '^#' "$PROJECT_DIR/.env" | xargs)
else
  echo "Ошибка: .env файл не найден!"
  exit 1
fi

docker run --rm \
  --entrypoint "" \
  --network shvirtd-example-python_backend \
  -e MYSQL_PWD="${MYSQL_ROOT_PASSWORD}" \
  -v ${BACKUP_DIR}:/backup \
  schnitzler/mysqldump \
  mysqldump --protocol=tcp --no-tablespaces -h db -uroot ${MYSQL_DATABASE} > ${BACKUP_DIR}/dump_${MYSQL_DATABASE}_${DATE}.sql
